"""
Document Tampering Detection Service — PARAKH AI
Analyzes uploaded documents for signs of digital manipulation.

Detection signals:
  1. PDF metadata anomalies (creator/producer tool mismatch, suspicious dates)
  2. Edited/modified PDF flags in metadata
  3. Reused / duplicate certificate numbers across bidders
  4. Duplicate document hash detection (same file submitted by multiple bidders)
  5. Suspicious text patterns (altered numbers, copy-paste artifacts)
  6. Certificate number format violations

These are SIGNALS for officer review — not automatic disqualification.
Final determination remains with the Procurement Officer.
"""
import os
import re
import hashlib
import json
from datetime import datetime
from typing import Optional

try:
    import pymupdf as fitz
    PYMUPDF_AVAILABLE = True
except ImportError:
    try:
        import fitz
        PYMUPDF_AVAILABLE = True
    except ImportError:
        PYMUPDF_AVAILABLE = False


# ── Severity levels ───────────────────────────────────────────
SEVERITY_HIGH   = 'HIGH'
SEVERITY_MEDIUM = 'MEDIUM'
SEVERITY_LOW    = 'LOW'
SEVERITY_INFO   = 'INFO'


def compute_file_hash(filepath: str) -> Optional[str]:
    """Compute SHA-256 hash of file for duplicate detection."""
    try:
        h = hashlib.sha256()
        with open(filepath, 'rb') as f:
            for chunk in iter(lambda: f.read(65536), b''):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return None


def analyze_pdf_metadata(filepath: str) -> dict:
    """
    Extract and analyze PDF metadata for tampering signals.
    Uses PyMuPDF (fitz) to read XMP / DocInfo metadata.
    """
    signals = []
    metadata = {}

    if not PYMUPDF_AVAILABLE:
        return {'metadata': {}, 'signals': [], 'tampered': False}

    try:
        doc = fitz.open(filepath)
        meta = doc.metadata or {}
        doc.close()

        metadata = {
            'creator':    meta.get('creator', ''),
            'producer':   meta.get('producer', ''),
            'author':     meta.get('author', ''),
            'subject':    meta.get('subject', ''),
            'title':      meta.get('title', ''),
            'created':    meta.get('creationDate', ''),
            'modified':   meta.get('modDate', ''),
            'encrypted':  meta.get('encryption', ''),
        }

        creator  = (meta.get('creator', '') or '').lower()
        producer = (meta.get('producer', '') or '').lower()
        created  = meta.get('creationDate', '') or ''
        modified = meta.get('modDate', '') or ''

        # Signal 1: Edited in a generic PDF editor (not generated by original issuer system)
        EDITOR_TOOLS = [
            'adobe acrobat', 'foxit', 'nitro', 'smallpdf', 'ilovepdf',
            'pdf editor', 'pdfedit', 'sejda', 'pdf24', 'pdfforge',
            'pdfsam', 'inkscape', 'gimp', 'photoshop', 'libreoffice draw',
            'pdf candy', 'wondershare', 'docfly', 'pdfillerpro', 'pdffiller',
        ]
        LEGITIMATE_ISSUERS = [
            'gov', 'gstn', 'income tax', 'mca', 'udyam', 'epfo', 'esic',
            'microsoft word', 'reportlab', 'fpdf', 'oracle', 'sap', 'oracle reports',
            'tally', 'busy', 'zoho', 'cleartax',
        ]
        is_editor = any(t in creator or t in producer for t in EDITOR_TOOLS)
        is_legit  = any(t in creator or t in producer for t in LEGITIMATE_ISSUERS)

        if is_editor and not is_legit:
            signals.append({
                'type':     'EDITING_TOOL_DETECTED',
                'severity': SEVERITY_HIGH,
                'detail':   f"PDF was created/modified using an editing tool: creator='{meta.get('creator','')}', producer='{meta.get('producer','')}'",
                'advisory': 'Document may have been edited after original issuance. Request original from issuing authority.',
            })
        elif is_editor:
            signals.append({
                'type':     'EDITING_TOOL_POSSIBLE',
                'severity': SEVERITY_MEDIUM,
                'detail':   f"PDF producer indicates possible editing: producer='{meta.get('producer','')}'",
                'advisory': 'Verify document authenticity with issuing authority.',
            })

        # Signal 2: Creation date in the future (impossible for a legitimate certificate)
        if created:
            try:
                # PyMuPDF date format: D:YYYYMMDDHHmmSS
                date_str = created.replace('D:', '').strip()[:8]
                cert_year = int(date_str[:4])
                current_year = datetime.now().year
                if cert_year > current_year:
                    signals.append({
                        'type':     'FUTURE_CREATION_DATE',
                        'severity': SEVERITY_HIGH,
                        'detail':   f"PDF creation date is in the future: {created}",
                        'advisory': 'Creation date manipulation detected. Reject document.',
                    })
            except Exception:
                pass

        # Signal 3: Modified date significantly newer than creation date (potential post-issuance edit)
        if created and modified and created != modified:
            signals.append({
                'type':     'MODIFICATION_AFTER_CREATION',
                'severity': SEVERITY_MEDIUM,
                'detail':   f"PDF was modified after creation. Created: {created[:16]}, Modified: {modified[:16]}",
                'advisory': 'Document was altered after its original creation. Verify with issuing authority.',
            })

        # Signal 4: No metadata at all (deliberately stripped — suspicious for official docs)
        if not any([meta.get('creator'), meta.get('producer'), meta.get('author')]):
            signals.append({
                'type':     'MISSING_METADATA',
                'severity': SEVERITY_LOW,
                'detail':   'PDF has no creator/producer/author metadata. This may indicate metadata was intentionally stripped.',
                'advisory': 'Metadata removal can be a sign of tampering. Request document from issuing source.',
            })

    except Exception as e:
        signals.append({
            'type':     'METADATA_READ_ERROR',
            'severity': SEVERITY_INFO,
            'detail':   f'Could not read PDF metadata: {str(e)}',
            'advisory': 'Manual document verification recommended.',
        })

    return {
        'metadata': metadata,
        'signals': signals,
        'tampered': any(s['severity'] in (SEVERITY_HIGH,) for s in signals),
        'suspicious': any(s['severity'] in (SEVERITY_HIGH, SEVERITY_MEDIUM) for s in signals),
    }


def detect_suspicious_text_patterns(extracted_text: str, doc_type: str) -> list:
    """
    Detect suspicious patterns in extracted text.
    Looks for:
    - Altered certificate numbers (format violations)
    - Copy-paste artifacts
    - Inconsistent date formats
    - Numbers that don't match expected patterns
    """
    signals = []
    if not extracted_text or extracted_text.startswith('['):
        return signals

    # Check GSTIN format if present
    gstins = re.findall(r'\b\d{2}[A-Z]{5}\d{4}[A-Z]\d[Z][A-Z\d]\b', extracted_text)
    for gstin in gstins:
        state_code = int(gstin[:2])
        if state_code < 1 or state_code > 38:
            signals.append({
                'type':     'INVALID_GSTIN_STATE_CODE',
                'severity': SEVERITY_HIGH,
                'detail':   f"GSTIN '{gstin}' has invalid state code {state_code}. Valid range: 01–38.",
                'advisory': 'GSTIN may have been manually altered.',
            })

    # Check PAN format if present
    pans = re.findall(r'\b[A-Z]{5}\d{4}[A-Z]\b', extracted_text)
    for pan in pans:
        # 4th char must be entity type
        entity_chars = 'PCFABTLJG'
        if pan[3] not in entity_chars:
            signals.append({
                'type':     'INVALID_PAN_ENTITY_TYPE',
                'severity': SEVERITY_MEDIUM,
                'detail':   f"PAN '{pan}' has unusual entity code '{pan[3]}'. Expected one of: {entity_chars}",
                'advisory': 'PAN format anomaly detected. Verify with Income Tax database.',
            })

    # Udyam number format: UDYAM-XX-YY-XXXXXXX
    udyam_nos = re.findall(r'UDYAM-[A-Z]{2}-\d{2}-\d{7}', extracted_text)
    udyam_invalid = re.findall(r'UDYAM-\S+', extracted_text)
    for u in udyam_invalid:
        if not re.match(r'^UDYAM-[A-Z]{2}-\d{2}-\d{7}$', u):
            signals.append({
                'type':     'INVALID_UDYAM_FORMAT',
                'severity': SEVERITY_MEDIUM,
                'detail':   f"Udyam number '{u}' does not match standard format UDYAM-XX-YY-XXXXXXX.",
                'advisory': 'Udyam number format anomaly. Verify at udyamregistration.gov.in.',
            })

    # Detect repeated text blocks (copy-paste signature)
    lines = [l.strip() for l in extracted_text.split('\n') if len(l.strip()) > 20]
    seen = {}
    for line in lines:
        seen[line] = seen.get(line, 0) + 1
    duplicated = [l for l, c in seen.items() if c > 2]
    if duplicated:
        signals.append({
            'type':     'REPEATED_TEXT_BLOCKS',
            'severity': SEVERITY_LOW,
            'detail':   f"Found {len(duplicated)} text block(s) repeated >2 times. May indicate copy-paste artifact.",
            'advisory': 'Inspect document for copy-paste manipulation.',
        })

    return signals


def check_duplicate_hash(file_hash: str, current_doc_id: str, bidder_id: str, all_docs: list) -> list:
    """
    Check if this exact file has been submitted before by another bidder.
    Identical hash = identical file = possible reuse / sharing of certificates.
    """
    signals = []
    if not file_hash:
        return signals

    for doc in all_docs:
        if doc.get('id') == current_doc_id:
            continue
        if doc.get('file_hash') == file_hash and doc.get('bidder_id') != bidder_id:
            signals.append({
                'type':     'DUPLICATE_FILE_DETECTED',
                'severity': SEVERITY_HIGH,
                'detail':   f"Identical file (hash match) found in document {doc['id']} submitted by bidder {doc['bidder_id']}.",
                'advisory': 'Same certificate submitted by multiple bidders. Possible shared/reused document. Investigate immediately.',
            })
            break  # One match is enough to flag

    return signals


def check_duplicate_cert_numbers(extracted_text: str, current_doc_id: str, bidder_id: str,
                                  all_docs: list, doc_type: str) -> list:
    """
    Check if certificate numbers extracted from this document match those
    in documents submitted by OTHER bidders (certificate reuse).
    """
    signals = []
    if not extracted_text or extracted_text.startswith('['):
        return signals

    # Extract identifiers to check for duplicates
    identifiers = []
    if doc_type in ('GST', 'UDYAM', 'PAN', 'EPFO', 'ESIC', 'ISO9001', 'ISO27001', 'OEM'):
        gstins = re.findall(r'\b\d{2}[A-Z]{5}\d{4}[A-Z]\d[Z][A-Z\d]\b', extracted_text)
        identifiers.extend(('GSTIN', g) for g in gstins)
        pans = re.findall(r'\b[A-Z]{5}\d{4}[A-Z]\b', extracted_text)
        identifiers.extend(('PAN', p) for p in pans)
        udyam = re.findall(r'UDYAM-[A-Z]{2}-\d{2}-\d{7}', extracted_text)
        identifiers.extend(('UDYAM', u) for u in udyam)
        # ISO cert numbers
        iso_certs = re.findall(r'\b(?:cert(?:ificate)?\s*(?:no|number|#)?\.?\s*)([A-Z0-9/-]{6,20})\b',
                               extracted_text, re.IGNORECASE)
        identifiers.extend(('ISO_CERT', c.strip()) for c in iso_certs)

    for id_type, id_value in identifiers:
        for doc in all_docs:
            if doc.get('id') == current_doc_id:
                continue
            if doc.get('bidder_id') == bidder_id:
                continue  # Same bidder is OK
            other_text = doc.get('extracted_text', '') or ''
            if id_value and id_value in other_text:
                signals.append({
                    'type':     'CERTIFICATE_NUMBER_REUSE',
                    'severity': SEVERITY_HIGH,
                    'detail':   f"{id_type} '{id_value}' appears in document {doc['id']} from bidder {doc['bidder_id']}.",
                    'advisory': f"Same {id_type} used by multiple bidders. Verify whether the same legal entity submitted bids under different names.",
                })
                break

    return signals


def run_tampering_analysis(filepath: str, doc_id: str, bidder_id: str,
                            extracted_text: str, doc_type: str,
                            all_docs: list) -> dict:
    """
    Main entry point — run all tampering checks and return consolidated result.
    Called during document upload.
    """
    all_signals = []
    file_hash = None

    # 1. Metadata analysis (PDF only)
    if filepath and filepath.lower().endswith('.pdf') and os.path.exists(filepath):
        meta_result = analyze_pdf_metadata(filepath)
        all_signals.extend(meta_result.get('signals', []))
        file_hash = compute_file_hash(filepath)
    elif filepath and os.path.exists(filepath):
        file_hash = compute_file_hash(filepath)

    # 2. Duplicate file hash
    if file_hash:
        all_signals.extend(check_duplicate_hash(file_hash, doc_id, bidder_id, all_docs))

    # 3. Text pattern analysis
    all_signals.extend(detect_suspicious_text_patterns(extracted_text, doc_type))

    # 4. Certificate number reuse across bidders
    all_signals.extend(check_duplicate_cert_numbers(extracted_text, doc_id, bidder_id, all_docs, doc_type))

    # Aggregate severity
    if any(s['severity'] == SEVERITY_HIGH for s in all_signals):
        overall_risk = SEVERITY_HIGH
    elif any(s['severity'] == SEVERITY_MEDIUM for s in all_signals):
        overall_risk = SEVERITY_MEDIUM
    elif any(s['severity'] == SEVERITY_LOW for s in all_signals):
        overall_risk = SEVERITY_LOW
    else:
        overall_risk = None  # No tampering signals

    return {
        'doc_id':         doc_id,
        'file_hash':      file_hash,
        'tampered':       overall_risk == SEVERITY_HIGH,
        'suspicious':     overall_risk in (SEVERITY_HIGH, SEVERITY_MEDIUM),
        'tampering_risk': overall_risk,
        'signal_count':   len(all_signals),
        'signals':        all_signals,
        'analyzed_at':    datetime.now().isoformat(),
    }
