import React, { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  CheckCircle, AlertTriangle, XCircle, MinusCircle,
  ChevronRight, ArrowRight, Shield, RefreshCw, Upload
} from 'lucide-react'
import api from '../../services/api.js'
import { useAuth } from '../../context/AuthContext.jsx'
import { PageLoader } from '../../components/LoadingSkeleton.jsx'
import { useLanguage } from '../../context/LanguageContext.jsx'

const STATUS_CONFIG = {
  READY: { icon: CheckCircle, color: 'text-green-600', bg: 'bg-green-50 border-green-200', label: 'Ready' },
  WARNING: { icon: AlertTriangle, color: 'text-amber-600', bg: 'bg-amber-50 border-amber-200', label: 'Warning' },
  MISSING: { icon: MinusCircle, color: 'text-red-600', bg: 'bg-red-50 border-red-200', label: 'Missing' },
  NOT_APPLICABLE: { icon: MinusCircle, color: 'text-gray-400', bg: 'bg-gray-50 border-gray-200', label: 'N/A' },
}

export default function BidReadiness() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const { t } = useLanguage()
  const bidderId = user?.organization_id || 'BID-SUB-001'
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('ALL')

  useEffect(() => {
    api.get(`/bidder/readiness?bidder_id=${bidderId}&tender_id=GEM-DEMO-2026-001`)
      .then((res) => setData(res.data))
      .catch(console.error)
      .finally(() => setLoading(false))
  }, [bidderId])

  if (loading) return <PageLoader />
  if (!data) return <div className="p-6 text-red-500">Unable to load readiness data.</div>

  const items = data.items || []
  const filtered = filter === 'ALL' ? items : items.filter((i) => i.status === filter)

  const scoreColor = data.score >= 85 ? 'text-green-600' : data.score >= 70 ? 'text-amber-600' : 'text-red-600'
  const scoreBg = data.score >= 85 ? 'from-green-50 to-white border-green-200' : data.score >= 70 ? 'from-amber-50 to-white border-amber-200' : 'from-red-50 to-white border-red-200'

  return (
    <div className="p-6 space-y-5 max-w-3xl">
      <div className="flex items-center gap-1 text-xs text-gray-500">
        <span className="hover:text-blue-600 cursor-pointer" onClick={() => navigate('/bidder/dashboard')}>Dashboard</span>
        <ChevronRight size={12} />
        <span className="text-slate-700 font-medium">{t('ai_bid_readiness')}</span>
      </div>

      <h1 className="page-title">{t('ai_bid_readiness')}</h1>

      {/* Score Card */}
      <div className={`rounded-2xl border bg-gradient-to-b ${scoreBg} p-6`}>
        <div className="flex items-center gap-6">
          <div className="text-center">
            <p className={`text-5xl font-bold ${scoreColor}`}>{data.score}%</p>
            <p className="text-xs text-gray-500 mt-1 font-medium">{data.status?.replace('_', ' ')}</p>
          </div>
          <div className="flex-1">
            <p className="text-sm font-semibold text-slate-700 mb-3">GEM-DEMO-2026-001</p>
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-white/80 rounded-xl p-2.5 text-center border border-gray-100">
                <p className="text-lg font-bold text-red-600">{data.critical_issues}</p>
                <p className="text-[9px] text-gray-500">{t('critical_issues')}</p>
              </div>
              <div className="bg-white/80 rounded-xl p-2.5 text-center border border-gray-100">
                <p className="text-lg font-bold text-amber-600">{data.warnings}</p>
                <p className="text-[9px] text-gray-500">{t('warnings')}</p>
              </div>
              <div className="bg-white/80 rounded-xl p-2.5 text-center border border-gray-100">
                <p className="text-lg font-bold text-green-600">{data.ready_count}</p>
                <p className="text-[9px] text-gray-500">{t('ready')}</p>
              </div>
            </div>
          </div>
        </div>

        {data.missing_mandatory > 0 && (
          <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-xl flex items-start gap-2">
            <XCircle size={14} className="text-red-600 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-red-800 font-medium">
              {data.missing_mandatory} mandatory document{data.missing_mandatory > 1 ? 's are' : ' is'} missing.
              Your bid cannot be submitted until these are resolved.
            </p>
          </div>
        )}
      </div>

      {/* AI Advisory */}
      <div className="rounded-xl border border-blue-100 bg-blue-50 p-3 flex items-start gap-2">
        <Shield size={13} className="text-blue-600 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-blue-800 leading-relaxed">
          This readiness check is generated by PARAKH AI based on your uploaded documents and the tender requirements.
          It is advisory only. The final compliance verification is performed by the Procurement Officer.
        </p>
      </div>

      {/* Checklist */}
      <div className="card overflow-hidden">
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-gray-100">
          <h2 className="text-sm font-semibold text-slate-700">{t('requirement_checklist')}</h2>
          <div className="flex gap-1.5">
            {['ALL', 'MISSING', 'WARNING', 'READY'].map((s) => (
              <button
                key={s}
                onClick={() => setFilter(s)}
                className={`text-xs px-2.5 py-1 rounded-full font-medium transition-colors ${filter === s ? 'bg-blue-700 text-white' : 'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}
              >
                {s}
              </button>
            ))}
          </div>
        </div>
        <div className="divide-y divide-gray-50">
          {filtered.map((item) => {
            const cfg = STATUS_CONFIG[item.status] || STATUS_CONFIG.READY
            const Icon = cfg.icon
            return (
              <div key={item.req_id} className={`flex items-start gap-3 px-5 py-3.5 ${item.status !== 'READY' ? 'bg-orange-50/30' : ''}`}>
                <Icon size={15} className={`${cfg.color} flex-shrink-0 mt-0.5`} />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-slate-700">{item.title}</p>
                  <p className="text-xs text-gray-500 mt-0.5">{item.message}</p>
                </div>
                <span className={`status-badge text-[10px] border ${cfg.bg} ${cfg.color}`}>
                  {cfg.label}
                </span>
                {item.status !== 'READY' && (
                  <button
                    className="flex-shrink-0 text-xs text-blue-600 font-semibold hover:underline flex items-center gap-0.5"
                    onClick={() => navigate('/bidder/documents')}
                  >
                    {t('fix')} <ArrowRight size={11} />
                  </button>
                )}
              </div>
            )
          })}
        </div>
      </div>

      <div className="flex gap-3">
        <button className="btn-secondary flex-1 justify-center" onClick={() => navigate('/bidder/documents')}>
          <Upload size={14} /> {t('upload_documents')}
        </button>
        <button className="btn-primary flex-1 justify-center" onClick={() => navigate('/bidder/submit-bid')}>
          {t('proceed_to_submission')} <ArrowRight size={14} />
        </button>
      </div>
    </div>
  )
}
